### PR TITLE
New write bytes for Arctis 9 and new Arctis Series

### PR DESCRIPTION
**Pull request by warpunish**
It seems steel series changed request bytes in new productions of arctis devices

### CODE REVIEW

**Comment by centic9** [comment]
I am not the owner of this project but your PR would probably break support for all other Arctis models...

**Comment by atagulalan** [comment]
Hello @warpunish 

Thank you for your contribution.
This change would break all other Arctis headsets. Could you implement a check for device id?

Thank you.

**Comment by warpunish** [comment]
@atagulalan I did this following a blog that you posted on another issue. It seems they didn't change device id just the write byte and response index. I could check if there is a validation for newer products when i have free time. Until that time people can use this fork if they have purchased a new line of products, i guess. Don't mind the PR right now.

**Comment by atagulalan** [comment]
I am merging this, thank you for your contribution!

**Pull request merged**
